project_id = "hwifjctgavrhnjqrrvkf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "https://st-john-paul-ii-secondaryschool-nak.vercel.app"
additional_redirect_urls = ["https://st-john-paul-ii-secondaryschool-nak.vercel.app"]
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[analytics]
enabled = true
port = 54327
backend = "postgres"

[edge_runtime]
enabled = true
policy = "per_worker"
deno_version = 2
